# -*- coding: utf-8 -*-
#修改密码
# Form implementation generated from reading ui file '修改密码.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication, QMessageBox

from dao import UserDao
from entity.UserModel import User


class Ui_Form(QWidget):

    def __init__(self):
        super(Ui_Form,self).__init__()
        self.setWindowFlag(QtCore.Qt.WindowType.MSWindowsFixedSizeDialogHint) #只显示最小化和关键按钮
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(391, 283)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 30, 301, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.userNameLable = QtWidgets.QLabel(self.formLayoutWidget)
        self.userNameLable.setText(UserDao.currentUser.username) #设置当前用户的用户名
        self.userNameLable.setObjectName("userNameLable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userNameLable)
        self.oldpwdInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.oldpwdInput.setObjectName("oldpwdInput")
        #密文
        self.oldpwdInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.oldpwdInput)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.newpwdInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.newpwdInput.setObjectName("newpwdInput")
        self.newpwdInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.newpwdInput)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.new2pwdInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.new2pwdInput.setObjectName("new2pwdInput")
        self.new2pwdInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.new2pwdInput)
        self.submitbtn = QtWidgets.QPushButton(Form)
        self.submitbtn.setGeometry(QtCore.QRect(60, 230, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitbtn.setIcon(icon)
        self.submitbtn.setObjectName("submitbtn")

        #提交按钮绑定事件
        self.submitbtn.clicked.connect(self.modifyPwd)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "修改密码"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "原密码："))
        self.label_4.setText(_translate("Form", "新密码："))
        self.label_5.setText(_translate("Form", "确认新密码："))
        self.submitbtn.setText(_translate("Form", "提交"))

    #修改密码
    def modifyPwd(self):
        username=self.userNameLable.text()
        oldPwd=self.oldpwdInput.text()
        if oldPwd.strip()=="":
            QMessageBox.warning(None,'系统提示','请输入原密码！')
            return
        #判断原密码是否正确
        if oldPwd!=UserDao.currentUser.password:
            QMessageBox.warning(None, '系统提示', '原密码输入不正确！')
            return
        newPwd=self.newpwdInput.text()
        if newPwd.strip()=="":
            QMessageBox.warning(None, '系统提示', '请输入新密码！')
            return
        newPwd2 = self.new2pwdInput.text()
        if newPwd2.strip() == "":
            QMessageBox.warning(None, '系统提示', '请输入确认新密码！')
            return
        #判断新密码和确认新密码是否一致
        if newPwd != newPwd2 :
            QMessageBox.warning(None, '系统提示', '新密码输入不正确！')
            return
        user=User.my_constructor(username,oldPwd,newPwd)
        if UserDao.modifyPassword(user)>0:
            QMessageBox.information(None,'系统提示','密码修改成功')
            self.resetForm()
        else:
            QMessageBox.information(None, '系统提示', '密码修改失败')


    def resetForm(self):
        self.oldpwdInput.setText("")
        self.newpwdInput.setText("")
        self.new2pwdInput.setText("")

if __name__ == '__main__':
    app=QApplication(sys.argv)
    ui=Ui_Form()
    ui.show()

    sys.exit(app.exec())