# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '修改密码.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(391, 283)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 30, 301, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.userNameLable = QtWidgets.QLabel(self.formLayoutWidget)
        self.userNameLable.setText("")
        self.userNameLable.setObjectName("userNameLable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userNameLable)
        self.oldpwdInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.oldpwdInput.setObjectName("oldpwdInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.oldpwdInput)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.newpwdInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.newpwdInput.setObjectName("newpwdInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.newpwdInput)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.new2pwdInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.new2pwdInput.setObjectName("new2pwdInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.new2pwdInput)
        self.submitbtn = QtWidgets.QPushButton(Form)
        self.submitbtn.setGeometry(QtCore.QRect(60, 230, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitbtn.setIcon(icon)
        self.submitbtn.setObjectName("submitbtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "修改密码"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "原密码："))
        self.label_4.setText(_translate("Form", "新密码："))
        self.label_5.setText(_translate("Form", "确认新密码："))
        self.submitbtn.setText(_translate("Form", "提交"))
